CREATE TABLE internships(
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    role TEXT NOT NULL,
    field text NOT NULL,
    mode text CHECK (mode IN ('offline', 'hybrid')) NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    region text NOT NULL,
    company_mentor_email text,
    company_name text NOT NULL,
    internship_letter_url text NOT NULL,
    approved boolean NOT NULL DEFAULT FALSE,
    student_id uuid NOT NULL,
    college_mentor_id uuid NOT NULL,
    department_id uuid NOT NULL,
    institute_id uuid NOT NULL,
    company_mentor_id uuid,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'::text),
    FOREIGN KEY (student_id) REFERENCES students(uid),
    FOREIGN KEY (college_mentor_id) REFERENCES college_mentors(uid),
    FOREIGN KEY (company_mentor_id) REFERENCES company_mentors(uid),
    FOREIGN KEY (department_id) REFERENCES departments(uid),
    FOREIGN KEY (institute_id) REFERENCES institutes(uid)
);